<?php

namespace Database\Seeders;

use App\Helpers\Common\NestedSetSeeder;
use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$entries = [
			[
				'name'       => [
					'en' => 'Engineering',
					'fr' => 'Ingénierie',
					'es' => 'Ingenieria',
					'ar' => 'هندسة',
					'de' => 'Maschinenbau',
					'it' => 'Ingegneria',
					'ru' => 'Инженерное дело',
					'nl' => 'Engineering',
					'nb' => 'Engineering',
					'uk' => 'Інженерія',
					'pl' => 'Inżynieria',
					'ro' => 'Inginerie',
					'el' => 'Μηχανική',
					'pt' => 'Engenharia',
					'da' => 'Ingeniørarbejde',
					'sv' => 'Ingenjörsvetenskap',
					'fi' => 'Insinööritaito',
					'hu' => 'Mérnöki munka',
					'sr' => 'Инжењерство',
					'cs' => 'Strojírenství',
					'bg' => 'Инженерство',
					'hr' => 'Inženjerstvo',
					'et' => 'Inseneriteadus',
					'lt' => 'Inžinerija',
					'lv' => 'Inženierzinātne',
					'sk' => 'Strojárstvo',
					'sl' => 'Inženirstvo',
					'is' => 'Verkfræði',
					'sq' => 'Inxhinieri',
				],
				'slug'       => 'engineering',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Financial Services',
					'fr' => 'Services financiers',
					'es' => 'Servicios financieros',
					'ar' => 'الخدمات المالية',
					'de' => 'Finanzdienstleistungen',
					'it' => 'Servizi finanziari',
					'ru' => 'Финансовые услуги',
					'nl' => 'Financiële diensten',
					'nb' => 'Finansielle tjenester',
					'uk' => 'Фінансові послуги',
					'pl' => 'Usługi finansowe',
					'ro' => 'Servicii financiare',
					'el' => 'Χρηματοοικονομικές Υπηρεσίες',
					'pt' => 'Serviços financeiros',
					'da' => 'Finansielle tjenester',
					'sv' => 'Finansiella tjänster',
					'fi' => 'Rahoituspalvelut',
					'hu' => 'Pénzügyi szolgáltatások',
					'sr' => 'Финансијске услуге',
					'cs' => 'Finanční služby',
					'bg' => 'Финансови услуги',
					'hr' => 'Financijske usluge',
					'et' => 'Finantsteenused',
					'lt' => 'Finansinės paslaugos',
					'lv' => 'Finanšu pakalpojumi',
					'sk' => 'Finančné služby',
					'sl' => 'Finančne storitve',
					'is' => 'Fjármálaþjónusta',
					'sq' => 'Shërbime financiare',
				],
				'slug'       => 'financial-services',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Banking',
					'fr' => 'Banque',
					'es' => 'Bancos',
					'ar' => 'الخدمات المصرفية',
					'de' => 'Bankwesen',
					'it' => 'Bancario',
					'ru' => 'Банковское дело',
					'nl' => 'Bankieren',
					'nb' => 'Bankvirksomhet',
					'uk' => 'Банківська справа',
					'pl' => 'Bankowy',
					'ro' => 'Bancar',
					'el' => 'Τραπεζιτικές εργασίες',
					'pt' => 'Bancário',
					'da' => 'Bankvæsen',
					'sv' => 'Bankverksamhet',
					'fi' => 'Pankkitoiminta',
					'hu' => 'Banki szolgáltatások',
					'sr' => 'Банкарство',
					'cs' => 'Bankovnictví',
					'bg' => 'Банково дело',
					'hr' => 'Bankarstvo',
					'et' => 'Pangandus',
					'lt' => 'Bankininkystė',
					'lv' => 'Banku darbība',
					'sk' => 'Bankovníctvo',
					'sl' => 'Bančništvo',
					'is' => 'Bankastarfsemi',
					'sq' => 'Bankar',
				],
				'slug'       => 'banking',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Security & Safety',
					'fr' => 'Sécurité & Sureté',
					'es' => 'Seguridad',
					'ar' => 'السلامة والأمن',
					'de' => 'Sicherheit',
					'it' => 'Sicurezza e protezione',
					'ru' => 'Безопасность и охрана',
					'nl' => 'Beveiliging en veiligheid',
					'nb' => 'Sikkerhet og sikkerhet',
					'uk' => 'Безпека та безпека',
					'pl' => 'Bezpieczeństwo i ochrona',
					'ro' => 'Securitate și siguranță',
					'el' => 'Ασφάλεια & Ασφάλεια',
					'pt' => 'Segurança e proteção',
					'da' => 'Sikkerhed og tryghed',
					'sv' => 'Säkerhet och trygghet',
					'fi' => 'Turvallisuus ja suojaus',
					'hu' => 'Biztonság és védelem',
					'sr' => 'Безбедност и сигурност',
					'cs' => 'Bezpečnost a ochrana',
					'bg' => 'Сигурност и безопасност',
					'hr' => 'Sigurnost i zaštita',
					'et' => 'Turvalisus ja ohutus',
					'lt' => 'Saugumas ir apsauga',
					'lv' => 'Drošība un aizsardzība',
					'sk' => 'Bezpečnosť a ochrana',
					'sl' => 'Varnost in zaščita',
					'is' => 'Öryggi og öryggisráðstafanir',
					'sq' => 'Siguri dhe mbrojtje',
				],
				'slug'       => 'security-safety',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Training',
					'fr' => 'Formation',
					'es' => 'Formación',
					'ar' => 'تدريب',
					'de' => 'Ausbildung',
					'it' => 'Formazione',
					'ru' => 'Обучение',
					'nl' => 'Opleiding',
					'nb' => 'Opplæring',
					'uk' => 'Навчання',
					'pl' => 'Szkolenie',
					'ro' => 'Antrenamentul',
					'el' => 'Εκπαίδευση',
					'pt' => 'Treinamento',
					'da' => 'Træning',
					'sv' => 'Träning',
					'fi' => 'Koulutus',
					'hu' => 'Képzés',
					'sr' => 'Обука',
					'cs' => 'Školení',
					'bg' => 'Обучение',
					'hr' => 'Obuka',
					'et' => 'Koolitus',
					'lt' => 'Mokymai',
					'lv' => 'Apmācība',
					'sk' => 'Školenie',
					'sl' => 'Usposabljanje',
					'is' => 'Þjálfun',
					'sq' => 'Trajnim',
				],
				'slug'       => 'training',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Public Service',
					'fr' => 'Service public',
					'es' => 'Servicio público',
					'ar' => 'خدمة عامة',
					'de' => 'Öffentlicher Dienst',
					'it' => 'Servizio pubblico',
					'ru' => 'Государственная служба',
					'nl' => 'Openbare dienst',
					'nb' => 'Offentlig tjeneste',
					'uk' => 'Державна служба',
					'pl' => 'Służba publiczna',
					'ro' => 'Serviciu public',
					'el' => 'Δημόσια Υπηρεσία',
					'pt' => 'Serviço público',
					'da' => 'Offentlig tjeneste',
					'sv' => 'Offentlig tjänst',
					'fi' => 'Julkinen palvelu',
					'hu' => 'Közszolgálat',
					'sr' => 'Јавна служба',
					'cs' => 'Veřejná služba',
					'bg' => 'Обществена служба',
					'hr' => 'Javna služba',
					'et' => 'Avalik teenistus',
					'lt' => 'Viešoji tarnyba',
					'lv' => 'Valsts pakalpojums',
					'sk' => 'Verejná služba',
					'sl' => 'Javna služba',
					'is' => 'Opinber þjónusta',
					'sq' => 'Shërbimi publik',
				],
				'slug'       => 'public-service',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Real Estate',
					'fr' => 'Immobilier',
					'es' => 'Bienes raíces',
					'ar' => 'العقارات',
					'de' => 'Immobilie',
					'it' => 'Immobiliare',
					'ru' => 'Недвижимость',
					'nl' => 'Vastgoed',
					'nb' => 'Fast eiendom',
					'uk' => 'Нерухомість',
					'pl' => 'Nieruchomość',
					'ro' => 'Imobiliare',
					'el' => 'Ακίνητα',
					'pt' => 'Imóveis',
					'da' => 'Ejendom',
					'sv' => 'Fastigheter',
					'fi' => 'Kiinteistöt',
					'hu' => 'Ingatlan',
					'sr' => 'Непокретности',
					'cs' => 'Nemovitosti',
					'bg' => 'Недвижими имоти',
					'hr' => 'Nekretnine',
					'et' => 'Kinnisvara',
					'lt' => 'Nekilnojamasis turtas',
					'lv' => 'Nekustamais īpašums',
					'sk' => 'Nehnuteľnosti',
					'sl' => 'Nepremičnine',
					'is' => 'Fasteignir',
					'sq' => 'Pasuri të paluajtshme',
				],
				'slug'       => 'real-estate',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Independent & Freelance',
					'fr' => 'Indépendants & Freelance',
					'es' => 'Independiente y Autónomo',
					'ar' => 'مستقلة مستقلة',
					'de' => 'Unabhängig und freiberuflich',
					'it' => 'Indipendente e Freelance',
					'ru' => 'Независимый и фриланс',
					'nl' => 'Onafhankelijk & freelance',
					'nb' => 'Uavhengig og frilans',
					'uk' => 'Незалежний і позаштатний',
					'pl' => 'Niezależny i wolny strzelec',
					'ro' => 'Independent și Freelance',
					'el' => 'Ανεξάρτητος & Ελεύθερος Επαγγελματίας',
					'pt' => 'Independente e Freelance',
					'da' => 'Selvstændig & Freelance',
					'sv' => 'Oberoende & Frilans',
					'fi' => 'Itsenäinen ja freelance',
					'hu' => 'Független és szabadúszó',
					'sr' => 'Независан и фриленсер',
					'cs' => 'Nezávislý a na volné noze',
					'bg' => 'Независими и фрийланс',
					'hr' => 'Nezavisni i slobodni',
					'et' => 'Sõltumatu ja vabakutseline',
					'lt' => 'Nepriklausomas ir laisvai samdomas',
					'lv' => 'Neatkarīgs un ārštata',
					'sk' => 'Nezávislý a na voľnej nohe',
					'sl' => 'Neodvisni in samostojni',
					'is' => 'Sjálfstætt starfandi',
					'sq' => 'I pavarur dhe i pavarur',
				],
				'slug'       => 'independent-freelance',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'IT & Telecoms',
					'fr' => 'Informatique & Télécoms',
					'es' => 'TI y Telecomunicaciones',
					'ar' => 'تكنولوجيا المعلومات والاتصالات',
					'de' => 'IT und Telekommunikation',
					'it' => 'IT e telecomunicazioni',
					'ru' => 'ИТ и Телекоммуникации',
					'nl' => 'IT & Telecommunicatie',
					'nb' => 'IT og telekom',
					'uk' => 'ІТ і телекомунікації',
					'pl' => 'IT i Telekomunikacja',
					'ro' => 'IT și telecomunicații',
					'el' => 'Πληροφορική & Τηλεπικοινωνίες',
					'pt' => 'TI e Telecomunicações',
					'da' => 'IT og telekommunikation',
					'sv' => 'IT och telekom',
					'fi' => 'IT ja telekommunikaatio',
					'hu' => 'IT és telekommunikáció',
					'sr' => 'ИТ и телекомуникације',
					'cs' => 'IT a telekomunikace',
					'bg' => 'ИТ и телекомуникации',
					'hr' => 'IT i telekomunikacije',
					'et' => 'IT ja telekommunikatsioon',
					'lt' => 'IT ir telekomunikacijos',
					'lv' => 'IT un telekomunikācijas',
					'sk' => 'IT a telekomunikácie',
					'sl' => 'IT in telekomunikacije',
					'is' => 'Upplýsingatækni og fjarskipti',
					'sq' => 'IT dhe Telekomunikacion',
				],
				'slug'       => 'it-telecoms',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Marketing & Communication',
					'fr' => 'Marketing & Communication',
					'es' => 'Marketing y Comunicación',
					'ar' => 'الاتصالات التسويقية',
					'de' => 'Marketing & Kommunikation',
					'it' => 'Marketing e Comunicazione',
					'ru' => 'Маркетинг и коммуникации',
					'nl' => 'Marketing & Communicatie',
					'nb' => 'Markedsføring og kommunikasjon',
					'uk' => 'Маркетинг і комунікації',
					'pl' => 'Marketing i komunikacja',
					'ro' => 'Marketing & Comunicare',
					'el' => 'Μάρκετινγκ & Επικοινωνίας',
					'pt' => 'Marketing e Comunicação',
					'da' => 'Marketing og kommunikation',
					'sv' => 'Marknadsföring och kommunikation',
					'fi' => 'Markkinointi ja viestintä',
					'hu' => 'Marketing és kommunikáció',
					'sr' => 'Маркетинг и комуникација',
					'cs' => 'Marketing a komunikace',
					'bg' => 'Маркетинг и комуникации',
					'hr' => 'Marketing i komunikacija',
					'et' => 'Turundus ja kommunikatsioon',
					'lt' => 'Rinkodara ir komunikacija',
					'lv' => 'Mārketings un komunikācija',
					'sk' => 'Marketing a komunikácia',
					'sl' => 'Marketing in komunikacija',
					'is' => 'Markaðssetning og samskipti',
					'sq' => 'Marketing dhe Komunikim',
				],
				'slug'       => 'marketing-communication',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Babysitting & Nanny Work',
					'fr' => 'Garderie',
					'es' => 'Trabajo de niñera y Niñera',
					'ar' => 'خدمة مجالسة الأطفال و مربية',
					'de' => 'Babysitting & Kindermädchenarbeit',
					'it' => 'Lavoro di babysitter e tata',
					'ru' => 'Работа няней и сиделкой',
					'nl' => 'Babysitten en nannywerk',
					'nb' => 'Barnevakt og barnepikearbeid',
					'uk' => 'Робота няні та няні',
					'pl' => 'Opieka nad dziećmi i praca niani',
					'ro' => 'Babysitting & Bonă',
					'el' => 'Babysitting & Nanny Work',
					'pt' => 'Babysitting e trabalho de babá',
					'da' => 'Børnepasning og nanny-arbejde',
					'sv' => 'Barnpassning och nannyarbete',
					'fi' => 'Lastenvahtiminen ja lastenhoitajan työ',
					'hu' => 'Gyermekfelügyelet és nevelőnői munka',
					'sr' => 'Чување деце и рад дадиље',
					'cs' => 'Hlídání dětí a práce chůvy',
					'bg' => 'Гледане на деца и работа като бавачка',
					'hr' => 'Čuvanje djece i posao dadilje',
					'et' => 'Lapsehoidmine ja lapsehoidjatöö',
					'lt' => 'Vaikų priežiūra ir auklės darbas',
					'lv' => 'Bērnu pieskatīšana un aukles darbs',
					'sk' => 'Opatrovanie detí a práca opatrovateľky',
					'sl' => 'Varstvo otrok in delo varuške',
					'is' => 'Barnapössun og starf barnfóstru',
					'sq' => 'Kujdesi për fëmijë dhe puna e dado-s',
				],
				'slug'       => 'babysitting-nanny-work',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Human Resources',
					'fr' => 'Ressources humaines',
					'es' => 'Recursos humanos',
					'ar' => 'الموارد البشرية',
					'de' => 'Personalwesen',
					'it' => 'Risorse umane',
					'ru' => 'Человеческие ресурсы',
					'nl' => 'Personeelszaken',
					'nb' => 'Menneskelige ressurser',
					'uk' => 'Людські ресурси',
					'pl' => 'Zasoby ludzkie',
					'ro' => 'Resurse umane',
					'el' => 'Ανθρώπινο Δυναμικό',
					'pt' => 'Recursos Humanos',
					'da' => 'Menneskelige ressourcer',
					'sv' => 'Personalresurser',
					'fi' => 'Henkilöstöresurssit',
					'hu' => 'Emberi erőforrások',
					'sr' => 'Људски ресурси',
					'cs' => 'Lidské zdroje',
					'bg' => 'Човешки ресурси',
					'hr' => 'Ljudski resursi',
					'et' => 'Inimressursid',
					'lt' => 'Žmogiškieji ištekliai',
					'lv' => 'Cilvēkresursi',
					'sk' => 'Ľudské zdroje',
					'sl' => 'Človeški viri',
					'is' => 'Mannauður',
					'sq' => 'Burimet njerëzore',
				],
				'slug'       => 'human-resources',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Medical & Healthcare',
					'fr' => 'Médecine & Santé',
					'es' => 'Médico y Sanitario',
					'ar' => 'الطبية والرعاية الصحية',
					'de' => 'Medizin & Gesundheitswesen',
					'it' => 'Medicina e assistenza sanitaria',
					'ru' => 'Медицина и здравоохранение',
					'nl' => 'Medisch & Gezondheidszorg',
					'nb' => 'Medisinsk og helsevesen',
					'uk' => 'Медицина та охорона здоров\'я',
					'pl' => 'Medycyna i opieka zdrowotna',
					'ro' => 'Medical și asistență medicală',
					'el' => 'Ιατρική & Υγεία',
					'pt' => 'Medicina e Cuidados de Saúde',
					'da' => 'Medicinsk & sundhedspleje',
					'sv' => 'Medicin & hälso- och sjukvård',
					'fi' => 'Lääketiede ja terveydenhuolto',
					'hu' => 'Orvosi és egészségügyi',
					'sr' => 'Медицинска и здравствена заштита',
					'cs' => 'Lékařství a zdravotní péče',
					'bg' => 'Медицина и здравеопазване',
					'hr' => 'Medicinska i zdravstvena skrb',
					'et' => 'Meditsiin ja tervishoid',
					'lt' => 'Medicina ir sveikatos priežiūra',
					'lv' => 'Medicīna un veselības aprūpe',
					'sk' => 'Medicína a zdravotníctvo',
					'sl' => 'Medicina in zdravstveno varstvo',
					'is' => 'Læknisfræði og heilbrigðisþjónusta',
					'sq' => 'Mjekësi dhe kujdes shëndetësor',
				],
				'slug'       => 'medical-healthcare',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Tourism & Restaurants',
					'fr' => 'Tourisme & Restaurants',
					'es' => 'Turismo y Restaurantes',
					'ar' => 'السياحة والمطاعم',
					'de' => 'Tourismus & Gastronomie',
					'it' => 'Turismo e Ristoranti',
					'ru' => 'Туризм и рестораны',
					'nl' => 'Toerisme & Restaurants',
					'nb' => 'Turisme og restauranter',
					'uk' => 'Туризм і ресторани',
					'pl' => 'Turystyka i restauracje',
					'ro' => 'Turism și restaurante',
					'el' => 'Τουρισμός & Εστιατόρια',
					'pt' => 'Turismo e Restaurantes',
					'da' => 'Turisme og restauranter',
					'sv' => 'Turism och restauranger',
					'fi' => 'Matkailu ja ravintolat',
					'hu' => 'Turizmus és éttermek',
					'sr' => 'Туризам и ресторани',
					'cs' => 'Cestovní ruch a restaurace',
					'bg' => 'Туризъм и ресторанти',
					'hr' => 'Turizam i restorani',
					'et' => 'Turism ja restoranid',
					'lt' => 'Turizmas ir restoranai',
					'lv' => 'Tūrisms un restorāni',
					'sk' => 'Turizmus a reštaurácie',
					'sl' => 'Turizem in restavracije',
					'is' => 'Ferðamál og veitingastaðir',
					'sq' => 'Turizëm dhe Restorante',
				],
				'slug'       => 'tourism-restaurants',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
			[
				'name'       => [
					'en' => 'Transportation & Logistics',
					'fr' => 'Transport et Logistique',
					'es' => 'Transportación',
					'ar' => 'النقل والخدمات اللوجستية',
					'de' => 'Transport und Logistik',
					'it' => 'Trasporti e logistica',
					'ru' => 'Транспорт и логистика',
					'nl' => 'Transport & Logistiek',
					'nb' => 'Transport og logistikk',
					'uk' => 'Транспорт і логістика',
					'pl' => 'Transport i logistyka',
					'ro' => 'Transport & Logistica',
					'el' => 'Μεταφορές & Logistics',
					'pt' => 'Transporte e Logística',
					'da' => 'Transport og logistik',
					'sv' => 'Transport och logistik',
					'fi' => 'Kuljetus ja logistiikka',
					'hu' => 'Szállítás és logisztika',
					'sr' => 'Транспорт и логистика',
					'cs' => 'Doprava a logistika',
					'bg' => 'Транспорт и логистика',
					'hr' => 'Transport i logistika',
					'et' => 'Transport ja logistika',
					'lt' => 'Transportas ir logistika',
					'lv' => 'Transports un loģistika',
					'sk' => 'Doprava a logistika',
					'sl' => 'Transport in logistika',
					'is' => 'Samgöngur og flutningar',
					'sq' => 'Transport dhe Logjistikë',
				],
				'slug'       => 'transportation-logistics',
				'image_path' => 'app/default/categories/fa-folder-default.png',
				'icon_class' => null,
				'children'   => [],
			],
		];
		
		// Add or update columns
		$entries = $this->processCategoryEntries($entries);
		
		$tableName = (new Category())->getTable();
		
		$startPosition = NestedSetSeeder::getNextRgtValue($tableName);
		NestedSetSeeder::insertEntries($tableName, $entries, $startPosition);
	}
	
	/**
	 * Recursively process category entries and their children
	 *
	 * @param array $entries The category entries to process
	 * @param int $depth The current depth level (0 for root)
	 * @return array Processed entries
	 */
	private function processCategoryEntries(array $entries, int $depth = 0): array
	{
		$processedEntries = [];
		
		foreach ($entries as $key => $entry) {
			// Set common properties for current entry
			$entry['description'] = null;
			$entry['parent_id'] = null;
			$entry['lft'] = 0;
			$entry['rgt'] = 0;
			$entry['depth'] = $depth;
			$entry['active'] = 1;
			
			// Process children recursively if they exist
			$children = $entry['children'] ?? [];
			if (!empty($children) && is_array($children)) {
				$entry['children'] = $this->processCategoryEntries($children, $depth + 1);
			}
			
			$processedEntries[$key] = $entry;
		}
		
		return $processedEntries;
	}
}
