<?php

namespace Database\Seeders;

use App\Helpers\Common\NestedSetSeeder;
use App\Models\Menu;
use App\Models\MenuItem;
use App\Models\Package;
use App\Models\PaymentMethod;
use App\Models\Role;
use Illuminate\Database\Seeder;

class MenuItemSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$this->runWithMenuId();
	}
	
	/**
	 * @param int|null $opMenuId
	 * @return void
	 */
	public function runWithMenuId(?int $opMenuId = null): void
	{
		// $appUrl = env('APP_URL');
		$appUrl = config('app.url');
		$isDemoDomain = (isDemoDomain($appUrl) || isDevEnv($appUrl));
		
		// Get menu items parameters
		$conditionsForGuest = ['guest' => 'true'];
		$conditionsForUser = ['auth' => 'true'];
		$conditionsForAuthenticUser = array_merge($conditionsForUser, ['authentic' => 'true']);
		$conditionsForImpersonating = array_merge($conditionsForUser, ['impersonating' => 'true']);
		$rolesForRecruiter = [Role::getSuperAdminRole(), Role::getRecruiterRole()];
		$rolesForJobseeker = [Role::getJobseekerRole()];
		$rolesForAdminUser = [Role::getSuperAdminRole()];
		if ($isDemoDomain) {
			$demoAdminRole = 'admin';
			$rolesForRecruiter = collect($rolesForRecruiter)->add($demoAdminRole)->toArray();
			$rolesForAdminUser = collect($rolesForAdminUser)->add($demoAdminRole)->toArray();
		}
		
		$logInText = [
			'en' => "Log In",
			'fr' => "Se connecter",
			'es' => "Iniciar sesión",
			'ar' => "تسجيل الدخول",
			'de' => "Anmelden",
			'it' => "Accedi",
			'ru' => "Войти",
			'nl' => "Inloggen",
			'nb' => "Logg inn",
			'uk' => "Увійти",
			'pl' => "Zaloguj się",
			'ro' => "Autentificare",
			'el' => "Σύνδεση",
			'pt' => "Iniciar sessão",
			'da' => "Log ind",
			'sv' => "Logga in",
			'fi' => "Kirjaudu sisään",
			'hu' => "Bejelentkezés",
			'sr' => "Пријава",
			'cs' => "Přihlásit se",
			'bg' => "Вход",
			'hr' => "Prijava",
			'et' => "Logi sisse",
			'lt' => "Prisijungti",
			'lv' => "Pieslēgties",
			'sk' => "Prihlásiť sa",
			'sl' => "Prijava",
			'is' => "Innskráning",
			'sq' => "Hyr",
		];
		
		$signUpText = [
			'en' => "Sign Up",
			'fr' => "S'inscrire",
			'es' => "Registrarse",
			'ar' => "اشتراك",
			'de' => "Registrieren",
			'it' => "Registrati",
			'ru' => "Зарегистрироваться",
			'nl' => "Aanmelden",
			'nb' => "Registrer deg",
			'uk' => "Зареєструватися",
			'pl' => "Zarejestruj się",
			'ro' => "Înregistrare",
			'el' => "Εγγραφή",
			'pt' => "Registar",
			'da' => "Tilmelding",
			'sv' => "Registrera dig",
			'fi' => "Rekisteröidy",
			'hu' => "Regisztráció",
			'sr' => "Регистрација",
			'cs' => "Registrovat",
			'bg' => "Регистрация",
			'hr' => "Registriraj se",
			'et' => "Registreeru",
			'lt' => "Registruotis",
			'lv' => "Reģistrēties",
			'sk' => "Registrovať sa",
			'sl' => "Registracija",
			'is' => "Nýskráning",
			'sq' => "Regjistrohu",
		];
		
		$myAccountText = [
			'en' => "My Account",
			'fr' => "Mon compte",
			'es' => "Mi cuenta",
			'ar' => "حسابي",
			'de' => "Mein Konto",
			'it' => "Il mio account",
			'ru' => "Мой аккаунт",
			'nl' => "Mijn account",
			'nb' => "Min konto",
			'uk' => "Мій обліковий запис",
			'pl' => "Moje konto",
			'ro' => "Contul meu",
			'el' => "Ο λογαριασμός μου",
			'pt' => "Minha conta",
			'da' => "Min konto",
			'sv' => "Mitt konto",
			'fi' => "Tilini",
			'hu' => "Fiókom",
			'sr' => "Мој налог",
			'cs' => "Můj účet",
			'bg' => "Моят акаунт",
			'hr' => "Moj račun",
			'et' => "Minu konto",
			'lt' => "Mano paskyra",
			'lv' => "Mans konts",
			'sk' => "Môj účet",
			'sl' => "Moj račun",
			'is' => "Minn aðgangur",
			'sq' => "Llogaria ime",
		];
		
		$myListingsText = [
			'en' => "My listings",
			'fr' => "Mes annonces",
			'es' => "Mis listados",
			'ar' => "قوائمي",
			'de' => "Meine Anzeigen",
			'it' => "I miei annunci",
			'ru' => "Мои объявления",
			'nl' => "Mijn aanbiedingen",
			'nb' => "Mine annonser",
			'uk' => "Мої оголошення",
			'pl' => "Moje ogłoszenia",
			'ro' => "Anunțurile mele",
			'el' => "Οι καταχωρήσεις μου",
			'pt' => "Os meus anúncios",
			'da' => "Mine annoncer",
			'sv' => "Mina annonser",
			'fi' => "Omat ilmoitukseni",
			'hu' => "Hirdetéseim",
			'sr' => "Мои огласи",
			'cs' => "Moje inzeráty",
			'bg' => "Моите обяви",
			'hr' => "Moji oglasi",
			'et' => "Minu kuulutused",
			'lt' => "Mano skelbimai",
			'lv' => "Manas sludinājumi",
			'sk' => "Moje inzeráty",
			'sl' => "Moji oglasi",
			'is' => "Mínar skráningar",
			'sq' => "Listimet e mia",
		];
		
		$favouriteListings = [
			'en' => "Favourite listings",
			'fr' => "Annonces favorites",
			'es' => "Listados favoritos",
			'ar' => "القوائم المفضلة",
			'de' => "Favoritenliste",
			'it' => "Annunci preferiti",
			'ru' => "Избранные списки",
			'nl' => "Favoriete aanbiedingen",
			'nb' => "Favorittannonser",
			'uk' => "Улюблені списки",
			'pl' => "Ulubione ogłoszenia",
			'ro' => "Anunțuri favorite",
			'el' => "Αγαπημένες καταχωρίσεις",
			'pt' => "Listagens favoritas",
			'da' => "Favoritannoncer",
			'sv' => "Favoritlistor",
			'fi' => "Suosikkilistaukset",
			'hu' => "Kedvenc hirdetések",
			'sr' => "Омиљени огласи",
			'cs' => "Oblíbené výpisy",
			'bg' => "Любими обяви",
			'hr' => "Omiljeni oglasi",
			'et' => "Lemmikkuutanded",
			'lt' => "Mėgstami skelbimai",
			'lv' => "Iecienītie sludinājumi",
			'sk' => "Obľúbené výpisy",
			'sl' => "Priljubljeni oglasi",
			'is' => "Uppáhalds skráningar",
			'sq' => "Listimet e preferuara",
		];
		
		$pricingText = [
			'en' => "Pricing",
			'fr' => "Tarification",
			'es' => "Precios",
			'ar' => "التسعير",
			'de' => "Preisgestaltung",
			'it' => "Prezzi",
			'ru' => "Ценообразование",
			'nl' => "Prijzen",
			'nb' => "Priser",
			'uk' => "Ціноутворення",
			'pl' => "Cennik",
			'ro' => "Prețuri",
			'el' => "Τιμολόγηση",
			'pt' => "Preços",
			'da' => "Priser",
			'sv' => "Prissättning",
			'fi' => "Hinnoittelu",
			'hu' => "Árazás",
			'sr' => "Цене",
			'cs' => "Cenění",
			'bg' => "Ценообразуване",
			'hr' => "Cijene",
			'et' => "Hinnakujundus",
			'lt' => "Kainodara",
			'lv' => "Cenu noteikšana",
			'sk' => "Ceny",
			'sl' => "Cenitev",
			'is' => "Verðlag",
			'sq' => "Çmimet",
		];
		
		$createListingText = [
			'en' => "Create Listing",
			'fr' => "Créer une annonce",
			'es' => "Crear listado",
			'ar' => "إنشاء قائمة",
			'de' => "Anzeige erstellen",
			'it' => "Crea elenco",
			'ru' => "Создать объявление",
			'nl' => "Aanbieding maken",
			'nb' => "Opprett annonse",
			'uk' => "Створити оголошення",
			'pl' => "Utwórz listing",
			'ro' => "Creează listare",
			'el' => "Δημιουργία καταχώρησης",
			'pt' => "Criar listagem",
			'da' => "Opret annonce",
			'sv' => "Skapa lista",
			'fi' => "Luo ilmoitus",
			'hu' => "Hirdetés létrehozása",
			'sr' => "Направи оглас",
			'cs' => "Vytvořit inzerát",
			'bg' => "Създаване на обява",
			'hr' => "Kreiraj oglas",
			'et' => "Loo kuulutus",
			'lt' => "Sukurti skelbimą",
			'lv' => "Izveidot sludinājumu",
			'sk' => "Vytvoriť inzerát",
			'sl' => "Ustvari seznam",
			'is' => "Búðu til skráningu",
			'sq' => "Krijo listim",
		];
		
		$profileText = [
			'en' => "Profile",
			'fr' => "Profil",
			'es' => "Perfil",
			'ar' => "الملف الشخصي",
			'de' => "Profil",
			'it' => "Profilo",
			'ru' => "Профиль",
			'nl' => "Profiel",
			'nb' => "Profil",
			'uk' => "Профіль",
			'pl' => "Profil",
			'ro' => "Profil",
			'el' => "Προφίλ",
			'pt' => "Perfil",
			'da' => "Profil",
			'sv' => "Profil",
			'fi' => "Profiili",
			'hu' => "Profil",
			'sr' => "Профил",
			'cs' => "Profil",
			'bg' => "Профил",
			'hr' => "Profil",
			'et' => "Profiil",
			'lt' => "Profilis",
			'lv' => "Profils",
			'sk' => "Profil",
			'sl' => "Profil",
			'is' => "Prófíll",
			'sq' => "Profili",
		];
		
		$messengerText = [
			'en' => "Messenger",
			'fr' => "Messagerie",
			'es' => "Mensajero",
			'ar' => "مراسل",
			'de' => "Messenger",
			'it' => "Messenger",
			'ru' => "Мессенджер",
			'nl' => "Messenger",
			'nb' => "Meldingstjeneste",
			'uk' => "Месенджер",
			'pl' => "Komunikator",
			'ro' => "Messenger",
			'el' => "Αγγελιοφόρος",
			'pt' => "Mensageiro",
			'da' => "Beskedtjeneste",
			'sv' => "Meddelande",
			'fi' => "Viestin",
			'hu' => "Üzenetküldő",
			'sr' => "Месинджер",
			'cs' => "Messenger",
			'bg' => "Месинджър",
			'hr' => "Messenger",
			'et' => "Sõnumitooja",
			'lt' => "Pranešimų programa",
			'lv' => "Ziņotājs",
			'sk' => "Messenger",
			'sl' => "Messenger",
			'is' => "Skilaboðastjóri",
			'sq' => "Mesazhërues",
		];
		
		$securityText = [
			'en' => "Security",
			'fr' => "Sécurité",
			'es' => "Seguridad",
			'ar' => "الأمان",
			'de' => "Sicherheit",
			'it' => "Sicurezza",
			'ru' => "Безопасность",
			'nl' => "Beveiliging",
			'nb' => "Sikkerhet",
			'uk' => "Безпека",
			'pl' => "Bezpieczeństwo",
			'ro' => "Securitate",
			'el' => "Ασφάλεια",
			'pt' => "Segurança",
			'da' => "Sikkerhed",
			'sv' => "Säkerhet",
			'fi' => "Turvallisuus",
			'hu' => "Biztonság",
			'sr' => "Безбедност",
			'cs' => "Zabezpečení",
			'bg' => "Сигурност",
			'hr' => "Sigurnost",
			'et' => "Turvalisus",
			'lt' => "Saugumas",
			'lv' => "Drošība",
			'sk' => "Zabezpečenie",
			'sl' => "Varnost",
			'is' => "Öryggi",
			'sq' => "Siguria",
		];
		
		$preferencesText = [
			'en' => "Preferences",
			'fr' => "Préférences",
			'es' => "Preferencias",
			'ar' => "التفضيلات",
			'de' => "Einstellungen",
			'it' => "Preferenze",
			'ru' => "Настройки",
			'nl' => "Voorkeuren",
			'nb' => "Innstillinger",
			'uk' => "Налаштування",
			'pl' => "Preferencje",
			'ro' => "Preferințe",
			'el' => "Προτιμήσεις",
			'pt' => "Preferências",
			'da' => "Indstillinger",
			'sv' => "Inställningar",
			'fi' => "Asetukset",
			'hu' => "Beállítások",
			'sr' => "Подешавања",
			'cs' => "Předvolby",
			'bg' => "Настройки",
			'hr' => "Postavke",
			'et' => "Eelistused",
			'lt' => "Nustatymai",
			'lv' => "Iestatījumi",
			'sk' => "Nastavenia",
			'sl' => "Nastavitve",
			'is' => "Stillingar",
			'sq' => "Preferencat",
		];
		
		$logOutText = [
			'en' => "Log Out",
			'fr' => "Se déconnecter",
			'es' => "Cerrar sesión",
			'ar' => "تسجيل الخروج",
			'de' => "Abmelden",
			'it' => "Esci",
			'ru' => "Выйти",
			'nl' => "Uitloggen",
			'nb' => "Logg ut",
			'uk' => "Вийти",
			'pl' => "Wyloguj",
			'ro' => "Deconectare",
			'el' => "Αποσύνδεση",
			'pt' => "Sair",
			'da' => "Log ud",
			'sv' => "Logga ut",
			'fi' => "Kirjaudu ulos",
			'hu' => "Kijelentkezés",
			'sr' => "Одјава",
			'cs' => "Odhlásit se",
			'bg' => "Изход",
			'hr' => "Odjava",
			'et' => "Logi välja",
			'lt' => "Atsijungti",
			'lv' => "Iziet",
			'sk' => "Odhlásiť sa",
			'sl' => "Odjava",
			'is' => "Skrá út",
			'sq' => "Dil",
		];
		
		$leaveText = [
			'en' => "Leave",
			'fr' => "Partir",
			'es' => "Salir",
			'ar' => "مغادرة",
			'de' => "Verlassen",
			'it' => "Uscire",
			'ru' => "Выйти",
			'nl' => "Vertrekken",
			'nb' => "Forlate",
			'uk' => "Піти",
			'pl' => "Wyjdź",
			'ro' => "Pleacă",
			'el' => "Αναχώρηση",
			'pt' => "Sair",
			'da' => "Forlad",
			'sv' => "Lämna",
			'fi' => "Poistu",
			'hu' => "Távozás",
			'sr' => "Напуштање",
			'cs' => "Opustit",
			'bg' => "Напусни",
			'hr' => "Napusti",
			'et' => "Lahku",
			'lt' => "Išeiti",
			'lv' => "Atstāt",
			'sk' => "Opustiť",
			'sl' => "Zapusti",
			'is' => "Fara",
			'sq' => "Dil",
		];
		
		// Get entries by menu location
		$entriesByMenu = [
			// HEADER
			'header' => [
				[
					'type'             => 'link',
					'icon'             => 'bi-grid-fill',
					'label'            => [
						'en' => "Browse Listings",
						'fr' => "Parcourir les annonces",
						'es' => "Explorar listados",
						'ar' => "تصفح القوائم",
						'de' => "Angebote durchsuchen",
						'it' => "Sfoglia elenchi",
						'ru' => "Просмотр списков",
						'nl' => "Bladeren door aanbiedingen",
						'nb' => "Bla gjennom annonser",
						'uk' => "Перегляд оголошень",
						'pl' => "Przeglądaj oferty",
						'ro' => "Răsfoiește anunțuri",
						'el' => "Περιήγηση σε καταχωρήσεις",
						'pt' => "Navegar nos anúncios",
						'da' => "Gennemse annoncer",
						'sv' => "Bläddra bland annonser",
						'fi' => "Selaa ilmoituksia",
						'hu' => "Hirdetések böngészése",
						'sr' => "Преглед огласа",
						'cs' => "Procházet nabídky",
						'bg' => "Разглеждане на обяви",
						'hr' => "Pregledaj oglase",
						'et' => "Sirvi kuulutusi",
						'lt' => "Naršyti skelbimus",
						'lv' => "Pārlūkot sludinājumus",
						'sk' => "Prehliadať inzeráty",
						'sl' => "Brskaj po oglasih",
						'is' => "Skoða skráningar",
						'sq' => "Shfleto listimet",
					],
					'url_type'         => 'route',
					'route_name'       => 'browse.listings',
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => null,
					'children'         => [],
				],
				[
					'type'             => 'link',
					'icon'             => 'fa-solid fa-tags',
					'label'            => $pricingText,
					'url_type'         => 'route',
					'route_name'       => 'pricing',
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => $conditionsForGuest,
					'description'      => 'Only for guests',
					'children'         => [],
				],
				[
					'type'             => 'link',
					'icon'             => 'fa-solid fa-tags',
					'label'            => $pricingText,
					'url_type'         => 'route',
					'route_name'       => 'pricing',
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => $conditionsForUser,
					'roles'            => $rolesForRecruiter,
					'description'      => 'For recruiters and for admin users (with the &quot;super-admin&quot; role)',
					'children'         => [],
				],
				[
					'type'             => 'button',
					'icon'             => 'fa-solid fa-pen-to-square',
					'label'            => $createListingText,
					'url_type'         => 'route',
					'route_name'       => 'listing.create.ms.showForm',
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => 'btn-highlight',
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => $conditionsForGuest,
					'description'      => 'Only for guests',
					'children'         => [],
				],
				[
					'type'             => 'button',
					'icon'             => 'fa-solid fa-pen-to-square',
					'label'            => $createListingText,
					'url_type'         => 'route',
					'route_name'       => 'listing.create.ms.showForm',
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => 'btn-highlight',
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => $conditionsForUser,
					'roles'            => $rolesForRecruiter,
					'description'      => 'For recruiters and for admin users (with the &quot;super-admin&quot; role)',
					'children'         => [],
				],
				// Auth Links (for Guests)
				[
					'type'             => 'link',
					'icon'             => 'fa-solid fa-user',
					'label'            => $logInText,
					'url_type'         => 'internal',
					'route_name'       => null,
					'route_parameters' => null,
					'url'              => '#',
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => $conditionsForGuest,
					'description'      => 'Only for guests',
					'children'         => [
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Log In",
							],
							'url_type'         => 'route',
							'route_name'       => 'auth.login.showForm',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForGuest,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => $signUpText,
							'url_type'         => 'route',
							'route_name'       => 'auth.register.showForm',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForGuest,
							'children'         => [],
						],
					],
				],
				
				// Account Links (for Recruiters)
				[
					'type'             => 'link',
					'icon'             => 'bi-person-circle',
					'label'            => [
						'en' => "{user.name}",
					],
					'url_type'         => 'internal',
					'route_name'       => null,
					'route_parameters' => null,
					'url'              => '#',
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => $conditionsForUser,
					'roles'            => $rolesForRecruiter,
					'description'      => 'For recruiters and for admin users (with the &quot;super-admin&quot; role)',
					'children'         => [
						[
							'type'             => 'link',
							'icon'             => 'fa-regular fa-building',
							'label'            => [
								'en' => "My companies",
								'fr' => "Mes entreprises",
								'es' => "Mis empresas",
								'ar' => "شركاتي",
								'de' => "Meine Unternehmen",
								'it' => "Le mie aziende",
								'ru' => "Мои компании",
								'nl' => "Mijn bedrijven",
								'nb' => "Mine bedrifter",
								'uk' => "Мої компанії",
								'pl' => "Moje firmy",
								'ro' => "Companiile mele",
								'el' => "Οι εταιρείες μου",
								'pt' => "Minhas empresas",
								'da' => "Mine virksomheder",
								'sv' => "Mina företag",
								'fi' => "Yritykseni",
								'hu' => "Vállalataim",
								'sr' => "Моје компаније",
								'cs' => "Moje společnosti",
								'bg' => "Моите компании",
								'hr' => "Moje tvrtke",
								'et' => "Minu ettevõtted",
								'lt' => "Mano įmonės",
								'lv' => "Mani uzņēmumi",
								'sk' => "Moje spoločnosti",
								'sl' => "Moja podjetja",
								'is' => "Fyrirtækin mín",
								'sq' => "Kompanitë e mia",
							],
							'url_type'         => 'route',
							'route_name'       => 'account.companies',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'roles'            => $rolesForRecruiter,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'fa-solid fa-list',
							'label'            => [
								'en' => "My Job Offers",
								'fr' => "Mes offres d'emploi",
								'es' => "Mis ofertas de trabajo",
								'ar' => "عروض عملي",
								'de' => "Meine Stellenangebote",
								'it' => "Le mie offerte di lavoro",
								'ru' => "Мои предложения о работе",
								'nl' => "Mijn vacatures",
								'nb' => "Mine jobbtilbud",
								'uk' => "Мої пропозиції роботи",
								'pl' => "Moje oferty pracy",
								'ro' => "Ofertele mele de muncă",
								'el' => "Οι προτάσεις εργασίας μου",
								'pt' => "Minhas ofertas de emprego",
								'da' => "Mine jobtilbud",
								'sv' => "Mina jobberbjudanden",
								'fi' => "Omat työpaikkailmoitukseni",
								'hu' => "Állásajánlataim",
								'sr' => "Моји понуде за посао",
								'cs' => "Moje pracovní nabídky",
								'bg' => "Моите предложения за работа",
								'hr' => "Moji poslovi",
								'et' => "Minu tööpakkumised",
								'lt' => "Mano darbo pasiūlymai",
								'lv' => "Mani darba piedāvājumi",
								'sk' => "Moje pracovné ponuky",
								'sl' => "Moja ponudba zaposlitve",
								'is' => "Mínar starfsboð",
								'sq' => "Ofertat e mia të punës",
							],
							'url_type'         => 'route',
							'route_name'       => 'account.listings.online',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'roles'            => $rolesForRecruiter,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-hourglass-split',
							'label'            => [
								'en' => "Pending approval",
								'fr' => "En attente d'approbation",
								'es' => "Aprobación pendiente",
								'ar' => "في انتظار الموافقة",
								'de' => "Ausstehende Genehmigung",
								'it' => "Approvazione in sospeso",
								'ru' => "Ожидает одобрения",
								'nl' => "In afwachting van goedkeuring",
								'nb' => "Venter på godkjenning",
								'uk' => "Очікує на схвалення",
								'pl' => "Oczekuje na zatwierdzenie",
								'ro' => "În așteptarea aprobării",
								'el' => "Εκκρεμεί έγκριση",
								'pt' => "Aprovação pendente",
								'da' => "Afventer godkendelse",
								'sv' => "Väntar på godkännande",
								'fi' => "Odottaa hyväksyntää",
								'hu' => "Jóváhagyásra vár",
								'sr' => "Чека одобрење",
								'cs' => "Čeká na schválení",
								'bg' => "Изчаква одобрение",
								'hr' => "Čeka odobrenje",
								'et' => "Ootab kinnitamist",
								'lt' => "Laukia patvirtinimo",
								'lv' => "Gaida apstiprinājumu",
								'sk' => "Čaká na schválenie",
								'sl' => "Čaka na odobritev",
								'is' => "Bíður samþykkis",
								'sq' => "Në pritje të aprovimit",
							],
							'url_type'         => 'route',
							'route_name'       => 'account.listings.pendingApproval',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'roles'            => $rolesForRecruiter,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-chat-text',
							'label'            => $messengerText,
							'url_type'         => 'route',
							'route_name'       => 'account.messages',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'divider',
							'icon'             => null,
							'label'            => null,
							'url_type'         => null,
							'route_name'       => null,
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => null,
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-person-lines-fill',
							'label'            => $myAccountText,
							'url_type'         => 'route',
							'route_name'       => 'account.overview',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-person-circle',
							'label'            => $profileText,
							'url_type'         => 'route',
							'route_name'       => 'account.profile',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-shield-lock',
							'label'            => $securityText,
							'url_type'         => 'route',
							'route_name'       => 'account.security',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-sliders',
							'label'            => $preferencesText,
							'url_type'         => 'route',
							'route_name'       => 'account.preferences',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-box-arrow-right',
							'label'            => $logOutText,
							'url_type'         => 'route',
							'route_name'       => 'auth.logout',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForAuthenticUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-box-arrow-right',
							'label'            => $leaveText,
							'url_type'         => 'route',
							'route_name'       => 'impersonate.leave',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForImpersonating,
							'children'         => [],
						],
						[
							'type'             => 'divider',
							'icon'             => null,
							'label'            => null,
							'url_type'         => null,
							'route_name'       => null,
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForAuthenticUser,
							'roles'            => $rolesForAdminUser,
							'description'      => 'Only for admin users (with the &quot;super-admin&quot; role)',
							'children'         => null,
						],
						[
							'type'             => 'link',
							'icon'             => 'fa-solid fa-gears',
							'label'            => [
								'en' => "Admin Panel",
							],
							'url_type'         => 'route',
							'route_name'       => 'admin.panel',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForAuthenticUser,
							'roles'            => $rolesForAdminUser,
							'description'      => 'Only for admin users (with the &quot;super-admin&quot; role)',
							'children'         => [],
						],
					],
				],
				
				// Account Links (for Jobseekers)
				[
					'type'             => 'button',
					'icon'             => 'bi-person-circle',
					'label'            => [
						'en' => "{user.name}",
					],
					'url_type'         => 'internal',
					'route_name'       => null,
					'route_parameters' => null,
					'url'              => '#',
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => 'btn-primary',
					'btn_outline'      => 1,
					'css_class'        => null,
					'conditions'       => $conditionsForUser,
					'roles'            => $rolesForJobseeker,
					'description'      => 'For jobseekers',
					'children'         => [
						[
							'type'             => 'link',
							'icon'             => 'fa-solid fa-paperclip',
							'label'            => [
								'en' => "My resumes",
							],
							'url_type'         => 'route',
							'route_name'       => 'account.resumes',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'roles'            => $rolesForJobseeker,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-bookmarks',
							'label'            => $favouriteListings,
							'url_type'         => 'route',
							'route_name'       => 'account.savedListings',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'roles'            => $rolesForJobseeker,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-chat-text',
							'label'            => $messengerText,
							'url_type'         => 'route',
							'route_name'       => 'account.messages',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'divider',
							'icon'             => null,
							'label'            => null,
							'url_type'         => null,
							'route_name'       => null,
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => null,
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-person-lines-fill',
							'label'            => $myAccountText,
							'url_type'         => 'route',
							'route_name'       => 'account.overview',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-person-circle',
							'label'            => $profileText,
							'url_type'         => 'route',
							'route_name'       => 'account.profile',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-shield-lock',
							'label'            => $securityText,
							'url_type'         => 'route',
							'route_name'       => 'account.security',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-sliders',
							'label'            => $preferencesText,
							'url_type'         => 'route',
							'route_name'       => 'account.preferences',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-box-arrow-right',
							'label'            => $logOutText,
							'url_type'         => 'route',
							'route_name'       => 'auth.logout',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForAuthenticUser,
							'description'      => 'Only for authentic users (Not impersonated)',
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => 'bi-box-arrow-right',
							'label'            => $leaveText,
							'url_type'         => 'route',
							'route_name'       => 'impersonate.leave',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForImpersonating,
							'description'      => 'Only for impersonated users',
							'children'         => [],
						],
					],
				],
			],
			
			// FOOTER
			'footer' => [
				[
					'type'             => 'title',
					'icon'             => null,
					'label'            => [
						'en' => "About Us",
						'fr' => "À propos de nous",
						'es' => "Sobre nosotros",
						'ar' => "معلومات عنا",
						'de' => "Über uns",
						'it' => "Chi siamo",
						'ru' => "О нас",
						'nl' => "Over ons",
						'nb' => "Om oss",
						'uk' => "Про нас",
						'pl' => "O nas",
						'ro' => "Despre noi",
						'el' => "Σχετικά με εμάς",
						'pt' => "Sobre nós",
						'da' => "Om os",
						'sv' => "Om oss",
						'fi' => "Meistä",
						'hu' => "Rólunk",
						'sr' => "O nama",
						'cs' => "O nás",
						'bg' => "За нас",
						'hr' => "O nama",
						'et' => "Meist",
						'lt' => "Apie mus",
						'lv' => "Par mums",
						'sk' => "O nás",
						'sl' => "O nas",
						'is' => "Um okkur",
						'sq' => "Rreth nesh",
					],
					'url_type'         => null,
					'route_name'       => null,
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => null,
					'children'         => [
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Terms",
								'fr' => "Conditions",
								'es' => "Términos",
								'ar' => "الشروط",
								'de' => "Nutzungsbedingungen",
								'it' => "Termini",
								'ru' => "Условия",
								'nl' => "Voorwaarden",
								'nb' => "Vilkår",
								'uk' => "Умови",
								'pl' => "Warunki",
								'ro' => "Termeni",
								'el' => "Όροι",
								'pt' => "Termos",
								'da' => "Vilkår",
								'sv' => "Villkor",
								'fi' => "Ehdot",
								'hu' => "Feltételek",
								'sr' => "Услови",
								'cs' => "Podmínky",
								'bg' => "Условия",
								'hr' => "Uvjeti",
								'et' => "Tingimused",
								'lt' => "Sąlygos",
								'lv' => "Noteikumi",
								'sk' => "Podmienky",
								'sl' => "Pogoji",
								'is' => "Skilmálar",
								'sq' => "Kushtet",
							],
							'url_type'         => 'route',
							'route_name'       => 'page.terms',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "FAQ",
								'fr' => "FAQ",
								'es' => "Preguntas frecuentes",
								'ar' => "الأسئلة الشائعة",
								'de' => "FAQ",
								'it' => "FAQ",
								'ru' => "ЧаВо",
								'nl' => "FAQ",
								'nb' => "FAQ",
								'uk' => "Поширені запитання",
								'pl' => "FAQ",
								'ro' => "Întrebări frecvente",
								'el' => "Συχνές ερωτήσεις",
								'pt' => "Perguntas frequentes",
								'da' => "Ofte stillede spørgsmål",
								'sv' => "Vanliga frågor",
								'fi' => "Usein kysytyt kysymykset",
								'hu' => "GYIK",
								'sr' => "Честа питања",
								'cs' => "Časté otázky",
								'bg' => "Често задавани въпроси",
								'hr' => "Često postavljana pitanja",
								'et' => "KKK",
								'lt' => "DUK",
								'lv' => "BUJ",
								'sk' => "Časté otázky",
								'sl' => "Pogosta vprašanja",
								'is' => "Algengar spurningar",
								'sq' => "Pyetjet e shpeshta",
							],
							'url_type'         => 'route',
							'route_name'       => 'page.faq',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Anti-Scam",
								'fr' => "Anti-Arnaque",
								'es' => "Anti-Estafa",
								'ar' => "مكافحة الاحتيال",
								'de' => "Anti-Betrug",
								'it' => "Anti-Truffa",
								'ru' => "Анти-Мошенничество",
								'nl' => "Anti-Oplichting",
								'nb' => "Anti-Svindel",
								'uk' => "Анти-Шахрайство",
								'pl' => "Anti-Oszustwo",
								'ro' => "Anti-Înșelăcie",
								'el' => "Αντι-Απάτη",
								'pt' => "Anti-Golpe",
								'da' => "Anti-Svindel",
								'sv' => "Anti-Bedrägeri",
								'fi' => "Anti-Huijaus",
								'hu' => "Anti-Csalás",
								'sr' => "Анти-Превара",
								'cs' => "Anti-Podvod",
								'bg' => "Анти-Измама",
								'hr' => "Anti-Prijevara",
								'et' => "Anti-Pettus",
								'lt' => "Anti-Sukčiavimas",
								'lv' => "Anti-Krāpšana",
								'sk' => "Anti-Podvod",
								'sl' => "Anti-Prevara",
								'is' => "And-Svindl",
								'sq' => "Anti-Mashtrim",
							],
							'url_type'         => 'route',
							'route_name'       => 'page.anti-scam',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Privacy",
								'fr' => "Confidentialité",
								'es' => "Privacidad",
								'ar' => "الخصوصية",
								'de' => "Datenschutz",
								'it' => "Privacy",
								'ru' => "Конфиденциальность",
								'nl' => "Privacy",
								'nb' => "Personvern",
								'uk' => "Конфіденційність",
								'pl' => "Prywatność",
								'ro' => "Confidențialitate",
								'el' => "Ιδιωτικότητα",
								'pt' => "Privacidade",
								'da' => "Privatliv",
								'sv' => "Integritet",
								'fi' => "Tietosuoja",
								'hu' => "Adatvédelem",
								'sr' => "Приватност",
								'cs' => "Soukromí",
								'bg' => "Поверителност",
								'hr' => "Privatnost",
								'et' => "Privaatsus",
								'lt' => "Privatumas",
								'lv' => "Privātums",
								'sk' => "Ochrana súkromia",
								'sl' => "Zasebnost",
								'is' => "Friðhelgi",
								'sq' => "Privatësia",
							],
							'url_type'         => 'route',
							'route_name'       => 'page.privacy',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
					],
				],
				[
					'type'             => 'title',
					'icon'             => null,
					'label'            => [
						'en' => "Contact & Sitemap",
						'fr' => "Contact & Plan du site",
						'es' => "Contacto & Mapa del sitio",
						'ar' => "اتصل & خريطة الموقع",
						'de' => "Kontakt & Sitemap",
						'it' => "Contatti & Mappa del sito",
						'ru' => "Контакты & Карта сайта",
						'nl' => "Contact & Sitemap",
						'nb' => "Kontakt & Sidemappe",
						'uk' => "Контакти & Мапа сайту",
						'pl' => "Kontakt & Mapa strony",
						'ro' => "Contact & Sitemap",
						'el' => "Επικοινωνία & Χάρτης ιστότοπου",
						'pt' => "Contacto & Mapa do site",
						'da' => "Kontakt & Oversigt over sitet",
						'sv' => "Kontakt & Webbplatskarta",
						'fi' => "Yhteystiedot & Sivukartta",
						'hu' => "Kapcsolat & Oldaltérkép",
						'sr' => "Контакт & Мапа сајта",
						'cs' => "Kontakt & Mapa stránek",
						'bg' => "Контакт & Карта на сайта",
						'hr' => "Kontakt & Mapa stranice",
						'et' => "Kontakt & Saidikaart",
						'lt' => "Kontaktai & Svetainės medis",
						'lv' => "Kontakti & Vietnes karte",
						'sk' => "Kontakt & Mapa stránok",
						'sl' => "Kontakt & Zemljevid spletnega mesta",
						'is' => "Hafa samband & Vefsjá",
						'sq' => "Kontakt & Harta e faqes",
					],
					'url_type'         => null,
					'route_name'       => null,
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => null,
					'children'         => [
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Contact Us",
								'fr' => "Contactez-nous",
								'es' => "Contáctenos",
								'ar' => "اتصل بنا",
								'de' => "Kontaktieren Sie uns",
								'it' => "Contattaci",
								'ru' => "Свяжитесь с нами",
								'nl' => "Neem contact met ons op",
								'nb' => "Kontakt oss",
								'uk' => "Зв'яжіться з нами",
								'pl' => "Skontaktuj się z nami",
								'ro' => "Contactați-ne",
								'el' => "Επικοινωνήστε μαζί μας",
								'pt' => "Contacte-nos",
								'da' => "Kontakt os",
								'sv' => "Kontakta oss",
								'fi' => "Ota yhteyttä",
								'hu' => "Lépjen kapcsolatba velünk",
								'sr' => "Контактирајте нас",
								'cs' => "Kontaktujte nás",
								'bg' => "Свържете се с нас",
								'hr' => "Kontaktirajte nas",
								'et' => "Võtke meiega ühendust",
								'lt' => "Susisiekite su mumis",
								'lv' => "Sazinies ar mums",
								'sk' => "Kontaktujte nás",
								'sl' => "Kontaktirajte nas",
								'is' => "Hafðu samband við okkur",
								'sq' => "Na kontaktoni",
							],
							'url_type'         => 'route',
							'route_name'       => 'contact.showForm',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Sitemap",
								'fr' => "Plan du site",
								'es' => "Mapa del sitio",
								'ar' => "خريطة الموقع",
								'de' => "Sitemap",
								'it' => "Mappa del sito",
								'ru' => "Карта сайта",
								'nl' => "Sitemap",
								'nb' => "Nettstedskart",
								'uk' => "Карта сайту",
								'pl' => "Mapa strony",
								'ro' => "Harta site-ului",
								'el' => "Χάρτης ιστότοπου",
								'pt' => "Mapa do site",
								'da' => "Sideoversigt",
								'sv' => "Webbplatskarta",
								'fi' => "Sivukartta",
								'hu' => "Oldaltérkép",
								'sr' => "Мапа сајта",
								'cs' => "Mapa stránek",
								'bg' => "Карта на сайта",
								'hr' => "Mapa stranice",
								'et' => "Sisukaart",
								'lt' => "Svetainės medis",
								'lv' => "Vietnes karte",
								'sk' => "Mapa stránok",
								'sl' => "Zemljevid spletnega mesta",
								'is' => "Veffangaskipan",
								'sq' => "Harta e faqes",
							],
							'url_type'         => 'route',
							'route_name'       => 'sitemap',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => [
								'en' => "Countries",
								'fr' => "Pays",
								'es' => "Países",
								'ar' => "الدول",
								'de' => "Länder",
								'it' => "Paesi",
								'ru' => "Страны",
								'nl' => "Landen",
								'nb' => "Land",
								'uk' => "Країни",
								'pl' => "Kraje",
								'ro' => "Țări",
								'el' => "Χώρες",
								'pt' => "Países",
								'da' => "Lande",
								'sv' => "Länder",
								'fi' => "Maat",
								'hu' => "Országok",
								'sr' => "Земље",
								'cs' => "Země",
								'bg' => "Държави",
								'hr' => "Zemlje",
								'et' => "Riigid",
								'lt' => "Šalys",
								'lv' => "Valstis",
								'sk' => "Krajiny",
								'sl' => "Države",
								'is' => "Lönd",
								'sq' => "Vende",
							],
							'url_type'         => 'route',
							'route_name'       => 'country.list',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => null,
							'children'         => [],
						],
					],
				],
				[
					'type'             => 'title',
					'icon'             => null,
					'label'            => $myAccountText,
					'url_type'         => null,
					'route_name'       => null,
					'route_parameters' => null,
					'url'              => null,
					'target'           => null,
					'nofollow'         => 0,
					'btn_class'        => null,
					'btn_outline'      => 0,
					'css_class'        => null,
					'conditions'       => null,
					'children'         => [
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => $logInText,
							'url_type'         => 'route',
							'route_name'       => 'auth.login.showForm',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForGuest,
							'description'      => 'Only for guests',
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => $signUpText,
							'url_type'         => 'route',
							'route_name'       => 'auth.register.showForm',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForGuest,
							'description'      => 'Only for guests',
							'children'         => [],
						],
						
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => $myAccountText,
							'url_type'         => 'route',
							'route_name'       => 'account.overview',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'description'      => 'Only for logged-in users',
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => $myListingsText,
							'url_type'         => 'route',
							'route_name'       => 'account.listings.online',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'description'      => 'Only for logged-in users',
							'children'         => [],
						],
						[
							'type'             => 'link',
							'icon'             => null,
							'label'            => $favouriteListings,
							'url_type'         => 'route',
							'route_name'       => 'account.savedListings',
							'route_parameters' => null,
							'url'              => null,
							'target'           => null,
							'nofollow'         => 0,
							'btn_class'        => null,
							'btn_outline'      => 0,
							'css_class'        => null,
							'conditions'       => $conditionsForUser,
							'description'      => 'Only for logged-in users',
							'children'         => [],
						],
					],
				],
			],
		];
		
		// Get the argument passed from admin controller
		$opMenuId = castToInt($opMenuId);
		
		// Get all menus
		$menus = Menu::query()->get();
		if ($menus->count() <= 0) {
			return;
		}
		
		// Get menus locations and they ID
		// i.e. Retrieve Menu ID by the $entriesByMenu key/location
		$menuLocations = $menus->pluck('id', 'location')->toArray();
		
		// Filter the $entriesByMenu with the requested Menu ID
		if (!empty($opMenuId)) {
			$menuIdsByLocation = collect($menuLocations)->flip()->toArray();
			$menuLocationFromDb = $menuIdsByLocation[$opMenuId] ?? null;
			
			$entriesByMenu = collect($entriesByMenu)
				->filter(function ($item, $key) use ($menuLocationFromDb) {
					return empty($menuLocationFromDb) || $key === $menuLocationFromDb;
				})->toArray();
		}
		
		// ---
		
		$tableName = (new MenuItem())->getTable();
		
		// Count activated packages & payment methods (to activate/disable the 'pricing' route)
		$countPackages = Package::query()->isActive()->count();
		$countPaymentMethods = PaymentMethod::query()->isActive()->count();
		$isPricingPageReady = ($countPackages > 0 && $countPaymentMethods > 0);
		
		// Get the app's timezone
		$timezone = config('app.timezone', 'UTC');
		
		// Process entries for each menu location
		foreach ($entriesByMenu as $menuLocation => $entries) {
			$menuIdFromDb = $menuLocations[$menuLocation] ?? null;
			
			// Process all entries (including nested children) recursively
			$processedEntries = $this->processMenuItemEntries(
				entries: $entries,
				menuId: $menuIdFromDb,
				depth: 0,
				isPricingPageReady: $isPricingPageReady,
				timezone: $timezone
			);
			
			$startPosition = NestedSetSeeder::getNextRgtValue($tableName);
			NestedSetSeeder::insertEntries($tableName, $processedEntries, $startPosition);
		}
	}
	
	/**
	 * Recursively process menu-item entries and their children
	 *
	 * @param array $entries The menu-item entries to process
	 * @param int|null $menuId The menu ID to assign
	 * @param int $depth The current depth level (0 for root)
	 * @param bool $isPricingPageReady Number of activated packages
	 * @param string $timezone Timezone for timestamps
	 * @return array Processed entries
	 */
	private function processMenuItemEntries(array $entries, ?int $menuId, int $depth, bool $isPricingPageReady, string $timezone): array
	{
		$processedEntries = [];
		
		foreach ($entries as $key => $entry) {
			// Set menu_id for current entry
			$entry['menu_id'] = $menuId ?? $entry['menu_id'] ?? null;
			
			// Process children recursively if they exist
			$children = $entry['children'] ?? [];
			if (!empty($children) && is_array($children)) {
				$entry['children'] = $this->processMenuItemEntries(
					entries: $children,
					menuId: $entry['menu_id'],
					depth: $depth + 1,
					isPricingPageReady: $isPricingPageReady,
					timezone: $timezone
				);
			}
			
			// Set active status based on route and package count
			$active = 1;
			$routeName = $entry['route_name'] ?? null;
			if ($routeName === 'pricing') {
				$active = $isPricingPageReady ? 1 : 0;
			}
			
			// Set common entry properties
			$entry['parent_id'] = null;
			$entry['lft'] = 0;
			$entry['rgt'] = 0;
			$entry['depth'] = $depth;
			$entry['active'] = $active;
			$entry['created_at'] = now($timezone)->format('Y-m-d H:i:s');
			$entry['updated_at'] = null;
			
			$processedEntries[$key] = $entry;
		}
		
		return $processedEntries;
	}
}
